<!DOCTYPE html>
<html>
    <body>
        <h1>New Car</h1>

        <div>
            <a href="/users">users list</a>
        </div>

        <br>

        <!-- BEGIN (write your solution here) -->
        <form action="/users" method="post" enctype="multipart/form-data">
            <div>
                <b>Email</b>
                <input type="text" name="user[email]" value="<?= htmlspecialchars($user['email'] ?? '') ?>">
                <?php if (isset($errors['email'])) : ?>
                    <div style="color: red"><?= $errors['email'] ?></div>
                <?php endif ?>
            </div>

            <br>

            <div>
                Name
                <input type="text" name="user[name]" value="<?= htmlspecialchars($user['name'] ?? '') ?>">
                <?php if (isset($errors['name'])) : ?>
                    <div style="color: red"><?= $errors['name'] ?></div>
                <?php endif ?>
            </div>
            
            <br>

            <div>
                Avatar
                <input type="file" name="user[avatar]">
                <?php if (isset($errors['avatar'])) : ?>
                    <div style="color: red"><?= $errors['avatar'] ?></div>
                <?php endif ?>
            </div>
            
            <br>

            <div>
                Password
                <input type="password" name="user[password]" value="">
                <?php if (isset($errors['password'])) : ?>
                    <div style="color: red"><?= $errors['password'] ?></div>
                <?php endif ?>
            </div>
            
            <br>

            <div>
                Password confirmation
                <input type="password" name="user[password_confirmation]" value="">
                <?php if (isset($errors['password_confirmation'])) : ?>
                    <div style="color: red"><?= $errors['password_confirmation'] ?></div>
                <?php endif ?>
            </div>
            
            <br>
            <div>
                <input type="submit">
            </div>
        </form>
        <!-- END -->

    </body>
</html>
