<a href="/">На главную</a>
<a href="/users">Список пользователей</a>
<h2>Профиль пользователя</h2>
<?= $uniqueUser['email'] ?>
<div style="width:70%;display:flex;justify-content:center;align-items:center;margin:20px auto;">
    <div style="width:70%;border:1px solid #bbb;display:flex;justify-content:center;align-items:center;flex-direction:column;background:#bbb;">
    
        <?php foreach ($user as $uniqueUser): ?>
            <div style="width:30%;height:300px;">
                <img src="<?= $uniqueUser['avatar'] ?>" style="width:100%;height:100%;">
            </div>
            <h3><?= $uniqueUser['name'] ?></h3>
            <p>Email: <?= $uniqueUser['email'] ?></p>
        <?php endforeach?>
    
    </div>
</div>
