<a href="/">На главную</a>
<a href="/users">Список пользователей</a>
<h2>Профиль пользователя</h2>

<div style="width:70%;display:flex;justify-content:center;align-items:center;margin:20px auto;">
    <div style="width:70%;border:1px solid #bbb;display:flex;justify-content:center;align-items:center;flex-direction:column;background:#bbb;">
        <div style="width:30%;height:300px;">
            <img src="<?= '/src/storage/'.$user['avatar'] ?>" style="width:100%;height:100%;">
        </div>
        <h3><?= $user['name'] ?></h3>
        <p>Email: <?= $user['email'] ?></p>
    </div>
</div>
